### ISSUE TITLE
Possibile bug/typo in data_provider_online_render.cpp

### ISSUE THREAD

**Issue by francescomilano172** [uzh-rpg/rpg_esim#16]
Good evening,

Should the following line in `data_provider_online_render.cpp` be `else if(next_t_flow_ < next_t_imu && next_t_flow_ < next_t_frame)` instead?
https://github.com/uzh-rpg/rpg_esim/blob/1241667c3358c90ba207fc388fb85b42bb8af5da/event_camera_simulator/esim_data_provider/src/data_provider_online_render.cpp#L368

(Sampling due to adaptive sampling, rather than due to minimum framerate/IMU rate).
With the current version, if I am not wrong, the `else if` above could in principle also capture the case in which `next_t_frame < next_t_flow_ < next_t_imu`, which should instead be handled by the later `else if`, at https://github.com/uzh-rpg/rpg_esim/blob/1241667c3358c90ba207fc388fb85b42bb8af5da/event_camera_simulator/esim_data_provider/src/data_provider_online_render.cpp#L375

In practice, I believe that there should be no difference, since `next_t_flow_` is always smaller than `next_t_frame`, as long as the `delta_t` of the adaptive sampling is smaller than `dt_frame_`<sup>*</sup>, but I thought that it could be worth asking for confirmation.

Thank you
___

<sup>*</sup>This by looking at the following lines:
https://github.com/uzh-rpg/rpg_esim/blob/1241667c3358c90ba207fc388fb85b42bb8af5da/event_camera_simulator/esim_data_provider/src/data_provider_online_render.cpp#L293
https://github.com/uzh-rpg/rpg_esim/blob/1241667c3358c90ba207fc388fb85b42bb8af5da/event_camera_simulator/esim_data_provider/src/data_provider_online_render.cpp#L296
https://github.com/uzh-rpg/rpg_esim/blob/1241667c3358c90ba207fc388fb85b42bb8af5da/event_camera_simulator/esim_data_provider/src/data_provider_online_render.cpp#L354

**Comment by supitalp** [comment]
Hi,
Yes you are absolutely correct, this is a typo. Fortunately, as you noted, this does not have an influence in practice.
I pushed the fix already.
Thanks for reporting!
Henri
