### ISSUE TITLE
Multi Objects 2D renderer not able to detect office.jpg and hence doesn't work

### ISSUE THREAD

**Issue by ashishrao7** [uzh-rpg/rpg_esim#18]
I have followed the instructions at this link (https://github.com/uzh-rpg/rpg_esim/wiki/Multi-Objects-2D-renderer) to render a simulation of  the multi objects 2D renderer. I have changed the absolute paths as instructed in the wiki. Below are the screenshots of that

![Screenshot from 2019-03-14 18-16-04](https://user-images.githubusercontent.com/12975862/54338396-cbfd8780-4657-11e9-8e08-0f3280a18612.png)

and

![Screenshot from 2019-03-14 18-16-28](https://user-images.githubusercontent.com/12975862/54338419-dc156700-4657-11e9-92b4-2d7f89ea4bbe.png)

This is the error message I get
![Screenshot from 2019-03-14 18-17-30](https://user-images.githubusercontent.com/12975862/54338439-e9caec80-4657-11e9-9d0c-da47cc50c304.png)

I can see that the files referenced by all the paths given in the config file exist. However the error message says that the package has some problem with opening office.jpg
I am able to get the Planar rendering running without any problems by only changing the absolute paths.

**Comment by supitalp** [comment]
Hello,
Given the error, it is very likely that the path is wrong.
Could you please double check that the path `home/ashish/sim_ws/src/rpg_esim/rpg_esim/imp/imp_planar_renderer/textures/office.jpg` is correct?

The `--path_to_sequence_file` variable in your config file seems to point to a different folder hierarchy: `/home/ashish/sim_ws/src/rpg_esim/event_camera_simulator/...`

Thanks.

**Comment by ashishrao7** [comment]
Thanks! That solved my problem. I should have looked at that part closer. I thought the later half of the address followed the default folder structure and didn't pay attention to it.
