### ISSUE TITLE
Rendering of frame and events in Multi Objects 2D renderer are not in sync

### ISSUE THREAD

**Issue by ashishrao7** [uzh-rpg/rpg_esim#19]
In the Multi Objects 2D renderer, there seems  to be an offset between the position of the object(in this case rugby ball) to the corresponding events that must be generated. This effect happens both while running the code on my system and in the demo video given in the wiki (https://www.youtube.com/watch?v=Yre8iS2LqPc&feature=youtu.be). Shouldn't the frame and events generated be in sync?

**Comment by supitalp** [comment]
Hi,
This time offset is normal.
To simulate a real DAVIS camera, the framerate of the camera images is artifically throttled to 40 fps (https://github.com/uzh-rpg/rpg_esim/blob/master/event_camera_simulator/esim_ros/cfg/multi_objects.conf#L24). This causes the events to be always "in advance" compared to the frames. This is also what you would observe with a real DAVIS sensor.

You can disable throttling the framerate of the images by setting the variable `ros_publisher_frame_rate` to a very high value (say, `1000000000`).
