### ISSUE TITLE
Simulation goes wrong for the test case

### ISSUE THREAD

**Issue by huangchaoxing** [uzh-rpg/rpg_esim#30]
When I launch :
roslaunch esim_ros esim.launch config:=cfg/example.conf

The package did run but pop out some error. And I am not able to get streams when launching the visualisation node.

F0713 01:10:49.247979  4073 camera_rig.cpp:106] Check failed: fileExists(FLAGS_calib_filename) Camera file does not exist.

[esim_node-2] process has died [pid 4073, exit code -6, cmd /home/engn6528/sim_ws/devel/lib/esim_ros/esim_node --v=1 --vmodule=data_provider_from_folder=10 --flagfile=/home/engn6528/sim_ws/src/rpg_esim/event_camera_simulator/esim_ros/cfg/example.conf __name:=esim_node __log:=/home/engn6528/.ros/log/3ad2778e-a4b7-11e9-b3f2-503eaaae86b5/esim_node-2.log].
log file: /home/engn6528/.ros/log/3ad2778e-a4b7-11e9-b3f2-503eaaae86b5/esim_node-2*.log

**Comment by ayman-saleh** [comment]
You need to change the absolute path in the cfg/example.conf file on line 15 and 18.
