### ISSUE TITLE
The differences between 'image_raw' and 'image_corrupted'

### ISSUE THREAD

**Issue by textstorm** [uzh-rpg/rpg_esim#41]
The output rosbag contain two topics named 'image_raw' and 'image_corrupted'. What is the differences between the two topics?

**Comment by supitalp** [comment]
Hello,
The images published on the `image_corrupted` topic have simulated motion blur (the simulated exposure time can be controlled by the parameter `--exposure_time` in the config file), while the images on the  `image_raw` topic are just ground truth images.

**Comment by textstorm** [comment]
thanks
