### ISSUE TITLE
build error for assimp_catkin

### ISSUE THREAD

**Issue by Marchinspring** [uzh-rpg/rpg_esim#42]
I met some problem while compiling the assimp library. The terrible campus network turn out to be blame. At the beginning, I have access to the Internet and Github, so I didn't notice it was the problem of network. After sending an email to Henri Rebecq, I found one important line which I ignored due to its light gray color on the window:

cd /home/xxc/sim_ws/build/assimp_catkin; catkin build --get-env assimp_catkin | catkin env -sl /usr/bin/make  --jobserver-fds=6,7 -j; cd -

When I run the above command, the output showed that the problem had been caused by the downloading failure of "assimp-4.0.1.zip" from "https://github.com/assimp/assimp/archive/v4.0.1.zip".

About the same time, Henri replied my email and reminded me of the network problem. Finally, I changed the network and complied the ESIM successfully. I really appreciate the work and advice of Henri.  I write it down here in case someone else got stuck in the same problem.

**Comment by supitalp** [comment]
Thanks for reporting the issue, hopefully it will help other people. Closing the issue now as the problem was fixed.
