### ISSUE TITLE
bug when contrast threshold < 0

### ISSUE THREAD

**Issue by eugenelyj** [uzh-rpg/rpg_esim#43]
It seems there will be a bug when contrast threshold smaller than zero (e.g `CHECK_GE(t, last_stamp_at_xy)` will failed). That is not rare. For example, if i set `constrast_threshold` to 0.10 and `contrast_sigma` to 0.05, it will be triggered often.

**Comment by supitalp** [comment]
Thanks, this is indeed a bug. I will push a fix soon. Meanwhile, you can fix it by setting a minimum sampled contrast threshold by adding the following two lines after this line: https://github.com/uzh-rpg/rpg_esim/blob/master/event_camera_simulator/esim/src/event_simulator.cpp#L60, inside the if condition:

```
constexpr ImageFloatType minimum_contrast_threshold = 0.01;
C = std::max(minimum_contrast_threshold, C);
```

This should fix the issue. Do not forget to recompile before checking.
Thanks,
Henri

**Comment by supitalp** [comment]
Fixed this: https://github.com/uzh-rpg/rpg_esim/commit/dc8a94f2b0d73aaf5a2b4af4d02759e027aa7d6b
