### ISSUE TITLE
ERROR: cannot launch node of type [esim_ros/esim_node]: can't locate node [esim_node] in package [esim_ros]

### ISSUE THREAD

**Issue by himanshu9345** [uzh-rpg/rpg_esim#50]
Hello, All
I have completed installation of rpg_esim (https://github.com/uzh-rpg/rpg_esim/wiki/Installation)
I am trying to install Planar Renderer (https://github.com/uzh-rpg/rpg_esim/wiki/Planar-Renderer).

1. Run two commands as follows
```
himanshu@himanshu-pc:~/sim_ws/src/rpg_esim/event_camera_simulator$ roscd esim_ros/
himanshu@himanshu-pc:~/sim_ws/src/rpg_esim/event_camera_simulator/esim_ros$ gedit cfg/example.conf
```
2. Then i changed the absolute path
![Screenshot from 2019-09-19 00-39-35](https://user-images.githubusercontent.com/8727605/65213947-1d0e8e00-da76-11e9-81a9-91d06d5750f6.png)

3. Run below code
`roslaunch esim_ros esim.launch config:=cfg/example.conf`

But, I got below error.
![Screenshot from 2019-09-19 00-25-03](https://user-images.githubusercontent.com/8727605/65214402-e0439680-da77-11e9-8bc3-b27caa5ae9e7.png)

**Comment by supitalp** [comment]
Hello,
Have you sourced your ROS workspace after compiling?
Please try do it as follows: `source ~/sim_ws/devel/setup.bash` and try to run ESIM again.

**Comment by himanshu9345** [comment]
Yes, I did it. 
I even used provided cmd but still same error.

**Comment by supitalp** [comment]
Hello,
OK. Did the installation process succeed (without yielding errors)? If the ROS workspace is sourced, and that esim_node cannot be found, it may be because it was not compiled.

**Comment by supitalp** [comment]
Also, what happens when you run this?

`rosrun esim_ros esim_node`

**Comment by himanshu9345** [comment]
Thank you, @supitalp. I recompiled it, and it worked. There was a compilation error before which I missed.
