### ISSUE TITLE
How to get the trajectory's moving function?

### ISSUE THREAD

**Issue by qwn19970728** [uzh-rpg/rpg_esim#51]

**Comment by supitalp** [comment]
Hello,
The camera trajectory is published on the `/tf` topic, and saved in the `/cam0/pose` topic in the saved rosbag. Does this answer your question?

**Comment by qwn19970728** [comment]
> Hello,
> The camera trajectory is published on the `/tf` topic, and saved in the `/cam0/pose` topic in the saved rosbag. Does this answer your question?



> Hello,
> The camera trajectory is published on the `/tf` topic, and saved in the `/cam0/pose` topic in the saved rosbag. Does this answer your question?



> Hello,
> The camera trajectory is published on the `/tf` topic, and saved in the `/cam0/pose` topic in the saved rosbag. Does this answer your question?

Thank you!

**Comment by qwn19970728** [comment]
> Hello,
> The camera trajectory is published on the `/tf` topic, and saved in the `/cam0/pose` topic in the saved rosbag. Does this answer your question?

Thank you!
