### ISSUE TITLE
Get simulated events

### ISSUE THREAD

**Issue by 24selttob** [uzh-rpg/rpg_esim#8]
Hello, 

The compilation worked fine and the simulation is running. 
I can visualize the simulation results properly but is there a way to get the simulated events created (x, y, timestamp, polarity) ?

**Comment by huangchaoxing** [comment]
Same question. How to simulate event using RGB input.

**Comment by supitalp** [comment]
Hello,
I am not sure I understand the question. Do you want to simulate events from a sequence of RGB images that you already have? (e.g., a video).
In that case, please read my answer here: https://github.com/uzh-rpg/rpg_esim/issues/11#issuecomment-457142736
